package io.prreviewassistant.review.context;

import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*;
import java.nio.charset.StandardCharsets; import java.util.List;
import io.prreviewassistant.github.auth.*; import io.prreviewassistant.github.client.*; import io.prreviewassistant.review.retrieval.*;
import org.junit.jupiter.api.Test; import org.springframework.util.unit.DataSize;

class ReviewContextBuilderTest {
    @Test void exactHeadAndBaseRevisionProvenanceAreRetained(){GitHubApiClient c=mock(GitHubApiClient.class);stubRepo(c);var s=snapshot(List.of(file("src/A.java",null,ChangedFileStatus.MODIFIED),file("src/Old.java",null,ChangedFileStatus.REMOVED)));stub(c,"src/A.java","a".repeat(40),"head");stub(c,"src/Old.java","b".repeat(40),"base");var r=builder(c,10,10,1024).build(s);assertThat(r.context().files()).extracting(ContextFile::revisionSide).contains(RepositoryRevisionSide.HEAD,RepositoryRevisionSide.BASE);verify(c).getRepositoryFile(eq(1L),eq("o"),eq("r"),eq("src/A.java"),eq("a".repeat(40)),anyInt());verify(c).getRepositoryFile(eq(1L),eq("o"),eq("r"),eq("src/Old.java"),eq("b".repeat(40)),anyInt());}
    @Test void optionalNotFoundIsPartialButAuthenticationAndRateLimitsRemainCritical(){GitHubApiClient c=mock(GitHubApiClient.class);stubRepo(c);var s=snapshot(List.of(file("src/A.java",null,ChangedFileStatus.MODIFIED)));var partial=builder(c,10,10,1024).build(s);assertThat(partial.outcome()).isEqualTo(ReviewContextBuildResult.Outcome.PARTIAL);assertThat(partial.context().omissions()).isEqualTo(partial.omissions());doThrow(GitHubException.rateLimited()).when(c).getRepositoryFile(anyLong(),anyString(),anyString(),anyString(),anyString(),anyInt());assertThatThrownBy(()->builder(c,10,10,1024).build(s)).isInstanceOfSatisfying(GitHubException.class,e->assertThat(e.type()).isEqualTo(GitHubErrorType.RATE_LIMITED));}
    @Test void binaryInvalidUtf8AndOversizeAreExplicitOmissions(){GitHubApiClient c=mock(GitHubApiClient.class);stubRepo(c);var s=snapshot(List.of(file("src/A.java",null,ChangedFileStatus.MODIFIED)));doReturn(new GitHubRepositoryFile(new byte[]{0,1},2)).when(c).getRepositoryFile(anyLong(),anyString(),anyString(),anyString(),anyString(),anyInt());assertThat(builder(c,10,10,1024).build(s).omissions().getFirst().reason()).isEqualTo(ContextOmissionReason.BINARY);doReturn(new GitHubRepositoryFile(new byte[]{(byte)0xc3,0x28},2)).when(c).getRepositoryFile(anyLong(),anyString(),anyString(),anyString(),anyString(),anyInt());assertThat(builder(c,10,10,1024).build(s).omissions().getFirst().reason()).isEqualTo(ContextOmissionReason.INVALID_TEXT);doReturn(new GitHubRepositoryFile("x".repeat(101).getBytes(StandardCharsets.UTF_8),101)).when(c).getRepositoryFile(anyLong(),anyString(),anyString(),anyString(),anyString(),anyInt());assertThat(builder(c,10,10,1024).build(s).omissions().getFirst().reason()).isEqualTo(ContextOmissionReason.FILE_TOO_LARGE);}
    @Test void budgetsStopRetrievalAndUsageIsAccurate(){GitHubApiClient c=mock(GitHubApiClient.class);stubRepo(c);var s=snapshot(List.of(file("src/A.java",null,ChangedFileStatus.MODIFIED),file("src/B.java",null,ChangedFileStatus.MODIFIED)));stub(c,"src/A.java","a".repeat(40),"12345");var r=builder(c,1,2,10).build(s);assertThat(r.context().budgetUsage().filesRetained()).isEqualTo(1);assertThat(r.context().budgetUsage().apiRequests()).isEqualTo(2);assertThat(r.context().budgetUsage().budgetExhausted()).isTrue();verify(c,never()).getRepositoryFile(eq(1L),eq("o"),eq("r"),eq("src/B.java"),anyString(),anyInt());}
    @Test void largeChangedFileWithoutAnchorIsOmittedInsteadOfRetainingItsBeginning(){GitHubApiClient c=mock(GitHubApiClient.class);stubRepo(c);var s=snapshot(List.of(file("../../x",null,ChangedFileStatus.MODIFIED),file("src/A.java",null,ChangedFileStatus.MODIFIED)));stub(c,"src/A.java","a".repeat(40),"fake-key\nhttps://attacker.invalid\nthird");var r=builder(c,10,10,1024).build(s);assertThat(r.context().files()).isEmpty();assertThat(r.omissions()).extracting(ContextOmission::reason).contains(ContextOmissionReason.NO_RELEVANT_FRAGMENT);assertThat(r.toString()).doesNotContain("fake-key","attacker","src/A.java");verify(c,never()).getRepositoryFile(anyLong(),anyString(),anyString(),eq("../../x"),anyString(),anyInt());}
    @Test void largeDirectJavaDependencyRetainsOnlyWindowAroundUniqueDeclaration(){GitHubApiClient c=mock(GitHubApiClient.class);stubRepo(c);String patch="import com.acme.PaymentRepository;";var s=snapshot(List.of(file("src/main/java/com/acme/Service.java",patch,ChangedFileStatus.MODIFIED)));String source="irrelevant secret\npublic interface PaymentRepository {\n  void save();\n}\ntrailing";stub(c,"src/main/java/com/acme/PaymentRepository.java","a".repeat(40),source);var r=builder(c,10,10,1024).build(s);ContextFile f=r.context().files().getFirst();assertThat(f.content()).contains("interface PaymentRepository","void save").doesNotContain("irrelevant secret","trailing");assertThat(f.complete()).isFalse();assertThat(f.startLine()).isEqualTo(2);assertThat(f.endLine()).isEqualTo(3);assertThat(f.revisionSide()).isEqualTo(RepositoryRevisionSide.HEAD);assertThat(f.revisionSha()).isEqualTo("a".repeat(40));assertThat(f.toString()).doesNotContain("PaymentRepository","void save");}
    private ReviewContextBuilder builder(GitHubApiClient c,int files,int requests,int total){int per=Math.min(100,total);return new ReviewContextBuilder(c,new ReviewContextProperties(true,files,DataSize.ofBytes(per),DataSize.ofBytes(total),DataSize.ofBytes(per),2,100,requests));}
    private void stubRepo(GitHubApiClient c){when(c.getRepository(1,2,PullRequestLoader.MAX_METADATA_RESPONSE_BYTES)).thenReturn(new GitHubRepositoryMetadata(2,"o","r"));doThrow(GitHubException.resourceNotFound()).when(c).getRepositoryFile(anyLong(),anyString(),anyString(),anyString(),anyString(),anyInt());}
    private void stub(GitHubApiClient c,String p,String sha,String text){byte[] b=text.getBytes(StandardCharsets.UTF_8);doReturn(new GitHubRepositoryFile(b,b.length)).when(c).getRepositoryFile(eq(1L),eq("o"),eq("r"),eq(p),eq(sha),anyInt());}
    private ChangedFile file(String p,String patch,ChangedFileStatus s){return new ChangedFile(p,null,s,1,0,1,patch==null?PatchAvailability.UNAVAILABLE:PatchAvailability.AVAILABLE,patch);}
    private PullRequestSnapshot snapshot(List<ChangedFile> f){return new PullRequestSnapshot(1,2,3,"a".repeat(40),"b".repeat(40),false,f);}
}
