package io.prreviewassistant.github.auth;

public enum GitHubErrorType {
    INVALID_CONFIGURATION,
    INVALID_INSTALLATION_ID,
    JWT_GENERATION_FAILED,
    AUTHENTICATION_REJECTED,
    INSTALLATION_NOT_FOUND,
    RATE_LIMITED,
    TRANSIENT_FAILURE,
    MALFORMED_RESPONSE
}
