package io.prreviewassistant.review.analysis;

public enum SuppressionReason {
    LOW_CONFIDENCE,
    BELOW_MINIMUM_SEVERITY,
    UNSUPPORTED_LOCATION,
    INSUFFICIENT_EVIDENCE,
    NOT_CHANGE_RELEVANT,
    GENERIC_OR_NON_ACTIONABLE,
    SEVERITY_INCONSISTENT,
    DUPLICATE,
    OVERLAPPING_FINDING,
    PUBLICATION_LIMIT
}
