package io.prreviewassistant.review.context;
public enum ContextOmissionReason { BINARY, INVALID_TEXT, FILE_TOO_LARGE, NO_RELEVANT_FRAGMENT, BUDGET_EXCEEDED, LOW_RELEVANCE, UNSUPPORTED_TYPE, NOT_FOUND, UNSAFE_PATH, GENERATED_OR_VENDORED, DISABLED }
